logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  config:
    import: "aws-parameterstore:/dev/"

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations:
      - classpath:db/migration
      - classpath:db/seed/dev

jwt:
  secret-key: ${JWT_SECRET_KEY}

cors:
  origin:
    - "http://localhost:3000"
    - "https://api-dev.eatda.net"
