logging:
  level:
    org.hibernate.SQL: INFO

spring:
  config:
    import: "aws-parameterstore:/prod/"

  datasource:
    url: ${RDS_ENDPOINT}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: false
    baseline-version: 0
    locations:
      - classpath:db/migration
      - classpath:db/seed/prod

jwt:
  secret-key: ${JWT_SECRET_KEY}

cors:
  origin:
    - "https://www.eatda.net"
    - "https://eatda.net"
